### PR TITLE
Ref: enable XRP for non-US countries

### PR DESCRIPTION
**Pull request by cmgustavo**

### CODE REVIEW

**Review by rastajpa — APPROVED** [review]
ACK!

**Comment by Gamboster** [comment]
It is also enabled for Crypto Swaps. We should remove it from there?

**Comment by Gamboster** [comment]
Should we allow NON-US users to do Crypto Swaps with XRP? It is currently disabled for all

**Comment by cmgustavo** [comment]
Closed in favor of https://github.com/bitpay/wallet/pull/11990

**Pull request closed without merging**
