### PR TITLE
WIP: [FEAT] card direct path

### PR DESCRIPTION
**Pull request by JohnathanWhite**
- remove card balance from advertisement svg
- fixed subtext spacing
- added direct path to login or signup from intro page

### CODE REVIEW

**Comment by 59999900440o** [comment]
Uploading 1.mp4…

**Comment by 59999900440o** [comment]
What's the point of using bitpay if I can't even activate a video that I can buy

**Comment by JohnathanWhite** [comment]
@cmgustavo I am waiting on the BitPay side of this to go in first

**Review by cmgustavo — APPROVED** [review]
LGTM!

**Pull request merged**
