### PR TITLE
[FEAT] RBF

### PR DESCRIPTION
**Pull request by gabrielbazan7**
BitPay

BitPay

BitPay

BitPay

### CODE REVIEW

**Review by rastajpa — APPROVED** [review]
ACK!

**Review by Gamboster — APPROVED** [review]
LGTM

**Comment by JohnathanWhite** [comment]
Copy adjustments ->

If enabled, your transactions will be marked as non-final, and you will have the possibility, while they are unconfirmed, to replace them with transactions that pay higher fees. Note that some merchants do not accept non-final transactions until they are confirmed.

also 

This transaction can be accelerated using a higher fee.

**Review by Gamboster — APPROVED** [review]
ACK

**Pull request merged**
