### PR TITLE
Add paper wallet sweep functionality for Bitcoin Cash

### LINKED ISSUE #6757: Support sweeping BCH paper wallets
It would be great to have Bitcoin Cash support for sweeping paper wallets.

### PR DESCRIPTION
**Pull request by EchterAgo**
@chaintip fixes #6757

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#6757](http://github.chaintip.org/bitpay/copay/issues/6757) first, @EchterAgo will claim the `0.02836039 BCH`| `~  28.85 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/32) and all future tips to the issue.

**Comment by EchterAgo** [comment]
I tested the BTC sweeping only by modifying return value in the debugger, I do not own any BTC to test with.

**Comment by EchterAgo** [comment]
I also added a small fix for the wallet getting stuck when sweeping fails. The onGoingProcessProvider was not being cleared in the error case.

**Comment by EchterAgo** [comment]
Another thing to note is that this is based on the v4.3.6 tag right now. I can not get master to build, it complains about missing fs-extras. I bisected the error back to the yarn commits.

This seems to be the reason why the code coverage tests fail, it is comparing between master and my commit. The changes can be rebased on top of master without conflicts.

**Pull request merged**
